### ISSUE TITLE
Make buyers react to better offers as they appear

### ISSUE THREAD

**Issue by svitkovsergey** [Axroy/WholesalePurchases#6]
Хотелось бы добавить покупателю возможность реагировать на изменение условий (открытие магазина с более выгодным предложением). Т.е. покупатель должен периодически заново делать поиск и решать стоит ли оставатьсяв текущей группе или переключится.

**Comment by Axroy** [comment]
почему это invalid?

**Comment by Axroy** [comment]
Proved: they do it already
